# Generated by Django 4.2.17 on 2024-12-30 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0002_alter_post_options_post_featured_image_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='dietary_categories',
            field=models.CharField(choices=[('Not-specify', 'Not-specify'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Gluten-Free', 'Gluten-Free'), ('Pescatarian', 'Pescatarian'), ('Dairy-Free', 'Dairy-Free')], default='Not-specify', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_cuisine',
            field=models.CharField(choices=[('British', 'British'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('French', 'French'), ('Mediterranean', 'Mediterranean'), ('Thai', 'Thai'), ('American', 'American'), ('Middle Eastern', 'Middle Eastern'), ('Other', 'Other')], default='British', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
