# Generated by Django 4.2.17 on 2024-12-31 00:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0003_remove_post_content_post_dietary_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='RecipeComment',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='RecipePost',
        ),
    ]
